### ISSUE TITLE
when using google analytics, accommodate for the case when it is blocked.. 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/analytics#3]
Starting in version 42, Firefox Desktop and Firefox for Android include built-in tracking protection. 
On this page https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection, it recommends to account for the case when Google Analytics is missing by checking to see if the ga object has initialized:

```
<a href="http://www.example.com" onclick="trackLink('http://www.example.com', event);">Visit example.com</a>
<script>
function trackLink(url,event) {
    event.preventDefault();
    if (window.ga && ga.loaded) {
         ga('send', 'event', 'outbound', 'click', url, {
         'transport': 'beacon',
         'hitCallback': function() { document.location = url; }
       });
    } else {
        document.location = url;
    }
}
</script>
```

**Comment by RFSH** [comment]
So the problem was that Tracking Protection plugins don't allow any connection to files that have "google analytics" in them. Therefore this solution wasn't helpful, because all of my google components have "google analytics" all over them.

I was able to find out if browser is blocking GA or not, by adding a [dummy](https://github.com/informatics-isi-edu/analytics/blob/master/static/js/test-google-analytics.js) javascript file.

You can test it in here: [http://analytics.arefsh.me/](http://analytics.arefsh.me/). It should show you this page:
![screen shot 2016-04-04 at 4 11 43 pm](https://cloud.githubusercontent.com/assets/2129750/14266832/14fbaa56-fa80-11e5-8a71-f7f65cc8471a.png)

**Comment by hongsudt** [comment]
@RFSH is this issue still relevant? If not, we should close it.

**Comment by RFSH** [comment]
@hongsudt It is fixed.
